version: '3.8'
services:
  postgres:
    container_name: orders-db
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=orders-db'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_USER=root'
    ports:
      - '5432:5432'
